api_platform:
    title: Wacdo back API Platform
    version: 1.0.0
    show_webby: false
    swagger:
        api_keys:
          JWT:
            name: Authorization
            type: header
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        jsonld:
            mime_types:
                - application/ld+json
        json:
            mime_types:
                - application/json