nelmio_api_doc:
    type_info: true
    documentation:
        openapi: "3.1.0"
        info:
            title: Wacdo back
            description: Documentation api v1 wacdo back
            version: 1.0.0

    areas: # to filter documented areas
        default:
            path_patterns: [ ^/api/v1/(?!/docs$) ]


