framework:
    validation:
        enabled: true
        translation_domain: validators
        enable_attributes: true
when@test:
    framework:
        validation:
            not_compromised_password: false
